# Generated by Django 4.1.5 on 2023-02-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_rename_quantity_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Test', max_length=20),
            preserve_default=False,
        ),
    ]
