# Generated by Django 3.2 on 2023-02-14 04:03

from django.db import migrations, models
import django.db.models.deletion
import inventory_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0007_auto_20230213_2252'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', inventory_system.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_system.address'),
        ),
    ]
