# Generated by Django 3.2 on 2023-02-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0008_auto_20230213_2303'),
    ]

    operations = [
    ]
